### ISSUE TITLE
Application sometimes fails to upload observations

### ISSUE THREAD

**Issue by samcrow** [samcrow/JRBPSurvey#8]
Reported by GI:

> b) Some tablets simply did not upload the survey data even after being connected to wifi.
> I restarted these tablets, and they started to work again. 
> When the app is uploading data, the status bar at the top of the app should appear blue with white > dots. 
> So if the app is constantly showing green bar even after entering the data, one should restart the > tablet (i.e. turn power off and turn it on again).

To do: Identify the hardware where this happened, reproduce.

**Comment by samcrow** [comment]
When testing uploading, I observed this:

```
08-07 22:27:56.359 21059-21767/org.samcrow.jrbpsurvey D/UploadService: Trying to upload...
08-07 22:27:56.359 21059-21767/org.samcrow.jrbpsurvey V/UploadService: Formatted observation: {Messor andrei=0, Hypoponera=0, Temnothrax sp.=0, ROUTE=Escobar, Stenamman sp=0, YEAR=2017, Pheidole californica=1, Liometopum occidentale=0, Solenopsis molesta=0, SURVEY LOCATION=531, NOTES=Test 2, Cardiocondyla mauritanica=0, Neivamyrme=0, TIME=22:20, Prenolepis imparis=0, Formica subpoleta=0, Formica sp.=0, DATESTAMP=20170807, Psedomyremex apache=0, Formica moki=0, Cremtogaster coarctata=1, DATE=08/07/2017 22:20:30, Unknown Species=0, Linepithema humile=0, Camponotus sp.=0, Aphenogaster occidentalis=0, Tapinoma sessile=0}
08-07 22:31:57.523 21059-21767/org.samcrow.jrbpsurvey V/UploadService: HTTP/1.1 302 Moved Temporarily
                                                                       Content-Type: text/html; charset=UTF-8
                                                                       Access-Control-Allow-Origin: *
                                                                       Cache-Control: no-cache, no-store, max-age=0, must-revalidate
                                                                       Pragma: no-cache
                                                                       Expires: Mon, 01 Jan 1990 00:00:00 GMT
                                                                       Date: Tue, 08 Aug 2017 05:36:13 GMT
                                                                       Location: https://script.googleusercontent.com/macros/echo?user_content_key=_w99ot_qb11nI452Id8zpIQEWFCPgQ22qzt7BybJxhYdOL6IehKS-vbgDndU-agMRyZ2iHcsWEaUXSPMdaaXBtL-9-10AerHm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnCd9dSriQrWpw4ecEL6RfheC_5oPCaXN593DHmqYnFqbOYwMaLcPbig3b8c1v9bgEaV-rV9yhQ38&lib=MA9N-6VLvZ7-NV-mmWtkNFNmPTUpaVvRV
                                                                       P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
                                                                       P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
                                                                       Content-Encoding: gzip
                                                                       X-Content-Type-Options: nosniff
                                                                       X-Frame-Options: SAMEORIGIN
                                                                       X-XSS-Protection: 1; mode=block
                                                                       Server: GSE
                                                                       Set-Cookie: NID=109=MR9FWat3xNv80UPce8tYZDIaip_jEvCNxfWSQkZEh0Fy4mFhBIelfMQ8jnC8dv7v69LgnB32WfEb_9J9aN5fERAr6M-GYz_NXlu2jn0_k4ipcyAwSZrC2SE_QARzOltB;Domain=.google.com;Path=/;Expires=Wed, 07-Feb-2018 05:36:13 GMT;HttpOnly
                                                                       Set-Cookie: NID=109=Mt_U_Q4gZy3RnrP9xju8VmrEI44zApkQ8DywV8qejgW9mUmJrOmD46Suq9JEot-LQCsQPbe4FVhh8asdoZcpPg0k_kF_CTLcE_-3zaLwEdN6WdinyJz6BQIP1GfMd-qA;Domain=.google.com;Path=/;Expires=Wed, 07-Feb-2018 05:36:13 GMT;HttpOnly
                                                                       Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
                                                                       Transfer-Encoding: chunked
                                                                       
                                                                       00001a8
                                                                       ���������������m�K��@���
                                                                       �Te���$h�G3��PAP7T���86�>�_5���ܺ�{6��D�;�iЭ�����\�0���<v����i�W���`����g�o�S}!����?z���ݯ��`!g�Lq�
                                                                       6}�4]p���I���Ij/�vP0V����������F�_/�2���ҫ��6=e�\-^��"�~֋HlsY���پ]��Fvy�N��	�KVXU�a᭻�R:�I���lå�C�5ZWTEy�c��qjܬ���auf
                                                                       �0�U�"�-�oa��V�pKy�N�y؃���<��'��#�N����-M�����r�iW٧,�]=�eV�l�䋚���"�Վ�F���?�e6�t�'�{ٿ�~,R�����e��a|Y��9�k�>�>�=Q>��]Ii@����
                                                                       0
08-07 22:31:57.625 21059-21767/org.samcrow.jrbpsurvey E/UploadService: Failed to parse page
                                                                       java.text.ParseException: Failed to parse response JSON (at offset 0)
                                                                           at org.samcrow.ridgesurvey.data.UploadService.upload(UploadService.java:203)
                                                                           at org.samcrow.ridgesurvey.data.UploadService.onHandleIntent(UploadService.java:116)
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:175)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                        Caused by: org.json.JSONException: Value HTTP of type java.lang.String cannot be converted to JSONObject
                                                                           at org.json.JSON.typeMismatch(JSON.java:111)
                                                                           at org.json.JSONObject.<init>(JSONObject.java:158)
                                                                           at org.json.JSONObject.<init>(JSONObject.java:171)
                                                                           at org.samcrow.ridgesurvey.data.UploadService.upload(UploadService.java:190)
                                                                           at org.samcrow.ridgesurvey.data.UploadService.onHandleIntent(UploadService.java:116) 
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:175) 
                                                                           at android.os.HandlerThread.run(HandlerThread.java:60) 
```

**Comment by samcrow** [comment]
Some upload attempts "succeed" in that the data appear in the spreadsheet, but the device does not get a response for a long time.

**Comment by samcrow** [comment]
I observed this again yesterday. I noticed that the date and time on the tablet were set incorrectly. After I set the date and time, it seemed to work.
